apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: go-fmt
  annotations:
    description: Performs a format check against all Go code within the repo
spec:
  resources:
    inputs:
    - name: repo
      type: git
  params:
  - name: setExitStatus
    description: Fail task if format issues are found
    type: string
    default: "true"
  steps:
  - name: pending-status
    image: bash:latest
    args:
    - -c
    - |
      echo "Starting task!"
  - name: fmt
    workingDir: "$(resources.inputs.repo.path)"
    image: golang:1.13
    script: |
      if [ "$(params.setExitStatus)" == "true" ]
      then
        exit `gofmt -l . | wc -l | xargs`
      else
        gofmt -l .
      fi
  - name: close-status
    image: bash:latest
    script: |
      #!/usr/bin/env bash
      echo "Task passed!"
