apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tekton-pipelines-default
  namespace: tekton-pipelines
rules:
- apiGroups:
  - ""
  resources:
  - pods/status
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tekton-pipelines-default
  namespace: tekton-pipelines
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: tekton-pipelines-default
subjects:
- kind: ServiceAccount
  name: default
  namespace: tekton-pipelines
