apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: go-lint
spec:
  pipelineSpec:
    tasks:
    - name: lint
      taskSpec:
        steps:
        - name: lint
          image: cytopia/golint:latest
          command:
          - go-lint
          args:
          - -set_exit_status
          - ./repo/...
