apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generareName: hello-world-
spec:
  pipelineSpec:
    tasks:
    - name: say-hello
      taskSpec:
        steps:
        - name: test
          image: bash:latest
          command:
          - echo
          args:
          - "Hello!"
